[project]
authors = ["Mira AMM"]
entry = "main.sw"
license = "Apache-2.0"
name = "get_amount_out_script"

[dependencies]
interfaces = { path = "../../libraries/interfaces" }
math = { path = "../../libraries/math" }
utils = { path = "../../libraries/utils" }
